### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by SamuelZhaoY** [macacajs/NoSmoke#41]

**Comment by SamuelZhaoY** [comment]
- [ ] support customized report paths
- [ ] fix bug for generating some empty images
- [ ] support image scanning and recognizing
